# -*- coding: utf-8 -*-
"""practica5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGtNMpYMv2-nZWLAoOlh7OhU2g4Vgst2
"""

'''
para cada variable(columna) de la base de datos iris obtener:
Su histograma, media, mediana y moda, su desviacion estandar y rango
'''
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Cargar el conjunto de datos
iris = pd.read_csv('C:/Users/legom/Documents/PCD\PCD_escom/iris.csv')

# Extraer las columnas necesarias
pw = iris["petal.width"]
pl = iris["petal.length"]
sw = iris["sepal.width"]
sl = iris["sepal.length"]

fig, ax = plt.subplots(2, 2, figsize=(15, 10))


ax[0,0].hist(pw, bins=15, alpha=0.7, color='blue', edgecolor='black')
ax[0,0].set_xlabel('Valor')
ax[0,0].set_ylabel('Frecuencia')

ax[0,1].hist(pl, bins=15, alpha=0.7, color='blue', edgecolor='black')
ax[0,1].set_xlabel('Valor')
ax[0,1].set_ylabel('Frecuencia')

ax[1,0].hist(sw, bins=15, alpha=0.7, color='blue', edgecolor='black')
ax[1,0].set_xlabel('Valor')
ax[1,0].set_ylabel('Frecuencia')

ax[1,1].hist(sl, bins=15, alpha=0.7, color='blue', edgecolor='black')
ax[1,1].set_xlabel('Valor')
ax[1,1].set_ylabel('Frecuencia')
#ordenamiento
def ord(x):
  if len(x) <= 1:
     return x
  else:
    pivot = x[len(x) // 2]
    left = [y for y in x if y < pivot]
    middle = [y for y in x if y == pivot]
    right = [y for y in x if y > pivot]
    return ord(left) + middle + ord(right)
#Media
def media(x):
  j=0
  for i in x:
    j+=i
  return(j/len(x))
#Mediana
def mediana(x):
  x=ord(x)
  n=len(x)
  if n%2 == 1:
    med=x[n//2]
  else:
    med=(x[n//2-1]+x[n//2])/2
  return(med)
#Rango
def rango(x):
  x=ord(x)
  n=len(x)
  r=x[n-1]-x[0]
  return(r)
#Moda
def moda(x):

  cont = {}

  for numero in x:
    if numero in cont:
      cont[numero] += 1
    else:
      cont[numero] = 1
  mayor=0
  moda= None

  for numero, frecuencia in cont.items():
    if frecuencia > mayor:
      mayor=frecuencia
      moda=numero
  return moda

#Desviacion estandar
def des(x):
  z=0
  for i in x:
    z+=(i-media(x))**2

  des=(z/(len(x)-1))**(0.5)
  return(des)


#imprimir media
print(f"La media de petal.width es {media(pw)}")
print(f"La media de petal.length es {media(pl)}")
print(f"La media de sepal.width es {media(sw)}")
print(f"La media de sepal.length es {media(sl)}")
#imprimir mediana
print(f"La mediana de petal.width es {mediana(pw)}")
print(f"La mediana de petal.length es {mediana(pl)}")
print(f"La mediana de sepal.width es {mediana(sw)}")
print(f"La mediana de sepal.length es {mediana(sl)}")
#imprimir moda
print(f"La moda de petal.width es {moda(pw)}")
print(f"La moda de petal.length es {moda(pl)}")
print(f"La moda de sepal.width es {moda(sw)}")
print(f"La moda de sepal.length es {moda(sl)}")
#imprimir desviacion estandar
print(f"La desviacion estandar de petal.width es {des(pw)}")
print(f"La desviacion estandar de petal.length es {des(pl)}")
print(f"La desviacion estandar de sepal.width es {des(sw)}")
print(f"La desviacion estandar de sepal.length es {des(sl)}")
#imprimir rango
print(f"El rango de petal.width es {rango(pw)}")
print(f"El rango de petal.length es {rango(pl)}")
print(f"El rango de sepal.width es {rango(sw)}")
print(f"El rango de sepal.length es {rango(sl)}")