# -*- coding: utf-8 -*-
"""Practica2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EcDzTWJqCHtuycDc-JLbaUwUEUPcux2n
"""

'''
crea una funcion que grafique un circulo.Las variables de entrada seran las coordenadas del centro del circulo
a,b, el radio y el color del circulo.Llamar a la funcion al menos 5 veces.
'''
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))

def circulo (a,b,r):

  p=np.linspace(0,2*np.pi,300)
  y=b+r*np.sin(p)
  x=a+r*np.cos(p)



  plt.ylim(-10,10)
  plt.xlim(-10,10)


  return plt.plot(x,y)

a=float(input('Ingresa las coordenas del centro'))
b=float(input('Ingresa las coordenas del centro'))
r=float(input('Ingresa las coordenas del radio'))

circulo(a,b,r)
circulo(a+2,b,r)
circulo(a,b+5,r)
circulo(a,b+4,r)
circulo(a+5,b,r)