# -*- coding: utf-8 -*-
"""practica3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQ8xj4HEqOhrrFkeQ99tJaOdsjVhnDkQ
"""

import matplotlib.pyplot as plt
from collections import Counter

# Leer el archivo y procesar el texto
lista = []
with open(r"C:\Users\legom\Documents\PCD\PCD_escom\xbox2.txt", encoding='utf8') as f:
    t = f.read()
t = t.replace('\n', ' ').replace('\r', ' ').replace('\t', ' ')
t = ' '.join(t.split())
palabras = t.split(' ')
cantidad_palabras = len(palabras)

print('Numero de palabras: ', cantidad_palabras)

# Contar las palabras
contar_palabras = Counter(palabras)

# Obtener las 20 palabras más frecuentes
palabras_frecuentes = contar_palabras.most_common(20)

print("Palabras más frecuentes:")
for palabra, frecuencia in palabras_frecuentes:
    print(f"{palabra}: {frecuencia}")

# Separar las palabras y sus frecuencias para la gráfica
palabras, frecuencias = zip(*palabras_frecuentes)

# Graficar
plt.figure(figsize=(10, 6))
plt.barh(palabras, frecuencias, color='skyblue')
plt.xlabel('Frecuencia')
plt.title('20 Palabras Más Frecuentes')
plt.gca().invert_yaxis()  # Invertir el eje y para que la palabra más frecuente esté en la parte superior
plt.show()