# -*- coding: utf-8 -*-
"""practica4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XbdYwh8pjIbSRmVjeF9EqNhUOQsUYQbJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Cargar el conjunto de datos
iris = pd.read_csv('C:/Users/legom/Documents/PCD\PCD_escom/iris.csv')

# Extraer las columnas necesarias
pw = iris["petal.width"]
pl = iris["petal.length"]
sw = iris["sepal.width"]
sl = iris["sepal.length"]
sz = iris["variety"]

# Crear un diccionario para asignar colores a cada subespecie
colors = {'Setosa': 'red', 'Versicolor': 'blue', 'Virginica': 'green'}

# Crear la figura y los ejes
fig, ax = plt.subplots(2, 3, figsize=(15, 10))

# Graficar cada combinación de características con colores diferentes
ax[0, 0].scatter(sl, sw, c=sz.map(colors), label=sz.unique())
ax[0, 0].set_title('A')
ax[0, 0].set_xlabel('Sepal Length')
ax[0, 0].set_ylabel('Sepal Width')

ax[0, 1].scatter(sl, pl, c=sz.map(colors))
ax[0, 1].set_title('B')
ax[0, 1].set_xlabel('Sepal Length')
ax[0, 1].set_ylabel('Petal Length')

ax[0, 2].scatter(sl, pw, c=sz.map(colors))
ax[0, 2].set_title('C')
ax[0, 2].set_xlabel('Sepal Length')
ax[0, 2].set_ylabel('Petal Width')

ax[1, 0].scatter(sw, pl, c=sz.map(colors))
ax[1, 0].set_title('D')
ax[1, 0].set_xlabel('Sepal Width')
ax[1, 0].set_ylabel('Petal Length')

ax[1, 1].scatter(sw, pw, c=sz.map(colors))
ax[1, 1].set_title('E')
ax[1, 1].set_xlabel('Sepal Width')
ax[1, 1].set_ylabel('Petal Width')

ax[1, 2].scatter(pl, pw, c=sz.map(colors))
ax[1, 2].set_title('F')
ax[1, 2].set_xlabel('Petal Length')
ax[1, 2].set_ylabel('Petal Width')

# Mostrar la leyenda
handles = [plt.Line2D([0], [0], marker='o', color='w', label=key,
                       markerfacecolor=value, markersize=10) for key, value in colors.items()]
ax[0, 0].legend(handles=handles, title="Variety")

plt.tight_layout()
plt.show()