# -*- coding: utf-8 -*-
"""practica 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgIL1l39JTnFzOhAdIBLVB7MpOGqaOPY
"""

import numpy as np
import matplotlib.pyplot as plt
import math

fig, ax=plt.subplots(2,3,figsize=(15,15), dpi=100)
f=100
c=100

x=np.random.randint(-5,6,size=(f,c))#arreglo de numeros enteros
y=np.random.randint(-5,6,size=(f,c))#arreglo de numeros enteros
d=np.random.randint(-5,6,size=(f,c))#arreglo de numeros enteros
e=np.random.randint(-5,6,size=(f,c))#arreglo de numeros enteros
g=np.random.randint(-5,6,size=(f,c))#arreglo de numeros enteros

for i in range(0,f):
  x[i,:]=i
  y[:,i]=i


centro=f//2
valormax=f//2+1
for i in range(f):
  for j in range(f):
    distancia = math.sqrt((i-centro)**2+(j-centro)**2)
    valor = valormax-round(distancia)
    e[i][j]= max(1,valor)

for i in range(f):
  for j in range(f):
    distancia = math.sqrt((i-centro)**2+(j-centro)**2)
    capa = round(distancia)
    d[i][j]= capa-1

for i in range(f):
  for j in range(f):
    distancia1=abs(i-centro)+abs(j-centro)
    valor=valormax-distancia1
    g[i][j]= max(1,valor)


ax[0,0].imshow(x,cmap='jet')
ax[0,0].set_title('A')
ax[0,1].imshow(y,cmap='jet')
ax[0,1].set_title('B')
ax[0,2].imshow(np.dot(x,y),cmap='jet')
ax[0,2].set_title('C')
ax[1,0].imshow(d,cmap='jet')
ax[1,0].set_title('D')
ax[1,1].imshow(e,cmap='jet')
ax[1,1].set_title('E')
ax[1,2].imshow(g,cmap='jet')
ax[1,2].set_title('F')